version: '3.9'

services:
  ranking-uploader:
    image: badrudduza/university-list:1.2
    container_name: ranking-uploader
    ports:
      - "4200:4200"
    restart: unless-stopped

  top-universities:
    image: badrudduza/top-universities:1.3
    container_name: top-universities
    environment:
      - RANKING_UPLOADER_URL=http://ranking-uploader:4200/rankings
      - TOP_N=5
    ports:
      - "4201:4201"
    depends_on:
      - ranking-uploader
    restart: unless-stopped